package mx.prisma.generadorPruebas.model;

// Generated Oct 27, 2015 5:08:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import mx.prisma.editor.model.CasoUso;

/**
 * ConfiguracionBaseDatos generated by hbm2java
 */
@Entity
@Table(name = "ConfiguracionBaseDatos", catalog = "PRISMA")
public class ConfiguracionBaseDatos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String urlBaseDatos;
	private String driver;
	private String usuario;
	private String contrasenia;
	private CasoUso casoUso;

	public ConfiguracionBaseDatos() {
	}

	public ConfiguracionBaseDatos(String urlBaseDatos, String driver,
			String usuario, String contrasenia, CasoUso casoUso) {
		this.urlBaseDatos = urlBaseDatos;
		this.driver = driver;
		this.usuario = usuario;
		this.contrasenia = contrasenia;
		this.casoUso = casoUso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "urlBaseDatos", nullable = false, length = 500)
	public String getUrlBaseDatos() {
		return this.urlBaseDatos;
	}

	public void setUrlBaseDatos(String urlBaseDatos) {
		this.urlBaseDatos = urlBaseDatos;
	}

	@Column(name = "driver", nullable = false, length = 50)
	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	@Column(name = "usuario", nullable = false, length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "contrasenia", nullable = false, length = 50)
	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CasoUsoElementoid", referencedColumnName ="Elementoid", nullable = false)
	public CasoUso getCasoUso() {
		return this.casoUso;
	}

	public void setCasoUso(CasoUso casoUso) {
		this.casoUso = casoUso;
	}

}
