package mx.prisma.generadorPruebas.model;

// Generated Oct 27, 2015 5:08:46 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import mx.prisma.editor.model.CasoUso;

/**
 * ConfiguracionHttp generated by hbm2java
 */
@Entity
@Table(name = "ConfiguracionHTTP", catalog = "PRISMA")
public class ConfiguracionHttp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String ip;
	private Integer puerto;
	private CasoUso casoUso;

	public ConfiguracionHttp() {
	}

	public ConfiguracionHttp(String ip, CasoUso casoUso) {
		this.ip = ip;
		this.casoUso = casoUso;
	}

	public ConfiguracionHttp(String ip, Integer puerto, CasoUso casoUso) {
		this.ip = ip;
		this.puerto = puerto;
		this.casoUso = casoUso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ip", nullable = false, length = 16)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "puerto")
	public Integer getPuerto() {
		return this.puerto;
	}

	public void setPuerto(Integer puerto) {
		this.puerto = puerto;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CasoUsoElementoid", referencedColumnName ="Elementoid", nullable = false)
	public CasoUso getCasoUso() {
		return this.casoUso;
	}

	public void setCasoUso(CasoUso casoUso) {
		this.casoUso = casoUso;
	}

}
