package mx.prisma.generadorPruebas.model;

// Generated 05-nov-2015 19:22:29 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EscenarioValorEntrada generated by hbm2java
 */
@Entity
@Table(name = "Escenario_ValorEntrada", catalog = "PRISMA")
public class EscenarioValorEntrada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Escenario escenario;
	private ValorEntrada valorEntrada;

	public EscenarioValorEntrada() {
	}

	public EscenarioValorEntrada(Escenario escenario, ValorEntrada valorEntrada) {
		this.escenario = escenario;
		this.valorEntrada = valorEntrada;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Escenarioid", referencedColumnName = "id")
	public Escenario getEscenario() {
		return this.escenario;
	}

	public void setEscenario(Escenario escenario) {
		this.escenario = escenario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ValorEntradaid", referencedColumnName = "id")	
	public ValorEntrada getValorEntradaid() {
		return this.valorEntrada;
	}

	public void setValorEntradaid(ValorEntrada valorEntrada) {
		this.valorEntrada = valorEntrada;
	}

}
