package mx.prisma.generadorPruebas.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonProperty;

import mx.prisma.editor.model.Entrada;
import mx.prisma.editor.model.ReglaNegocio;

/**
 * ValorEntrada generated by hbm2java
 */
@Entity
@Table(name = "ValorEntrada", catalog = "PRISMA")
public class ValorEntrada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Entrada entrada;
	private ReglaNegocio reglaNegocio;
	private String valor;
	private Boolean valido;
	private Boolean correcto;
	private Boolean registrado;
	private Boolean aleatorio;
	private Boolean insercion;
	private Boolean modificacion;
	private Boolean seleccionada;
	private Boolean nogenerable_prueba;
	private Boolean nogenerable_guion;
	private Boolean correcto_prueba;
	private Boolean correcto_guion;
	

	public ValorEntrada() {
	}

	public ValorEntrada(Entrada entrada, ReglaNegocio reglaNegocio, String valor) {
		this.entrada = entrada;
		this.reglaNegocio = reglaNegocio;
		this.valor = valor;
	}

	public ValorEntrada(Entrada entrada, ReglaNegocio reglaNegocio,
			String valor, Boolean valido) {
		this.entrada = entrada;
		this.reglaNegocio = reglaNegocio;
		this.valor = valor;
		this.valido = valido;
	}
	
	public ValorEntrada(Entrada entrada, String valor, Boolean valido,
			Boolean correcto, Boolean registrado, Boolean aleatorio, Boolean insercion, Boolean modificacion){
		this.entrada = entrada;
		this.valor = valor;
		this.valido = valido;
		this.correcto = correcto;
		this.registrado = registrado;
		this.aleatorio = aleatorio;
		this.insercion = insercion;
		this.modificacion = modificacion;
	}

	public ValorEntrada(Entrada entrada, String valor, Boolean valido,
			Boolean correcto, Boolean registrado, Boolean aleatorio, Boolean insercion, Boolean modificacion, Boolean seleccionada,Boolean correcto_prueba,Boolean correcto_guion){
		this.entrada = entrada;
		this.valor = valor;
		this.valido = valido;
		this.correcto = correcto;
		this.registrado = registrado;
		this.aleatorio = aleatorio;
		this.insercion = insercion;
		this.modificacion = modificacion;
		this.seleccionada = seleccionada;
		this.correcto_prueba = correcto_prueba;
		this.correcto_guion = correcto_guion;
	}
	
	public ValorEntrada(Entrada entrada, String valor, Boolean valido, Boolean correcto, Boolean registrado,
			Boolean aleatorio, Boolean insercion, Boolean modificacion, Boolean seleccionada){
		this.entrada = entrada;
		this.valor = valor;
		this.valido = valido;
		this.correcto = correcto;
		this.registrado = registrado;//ESTE
		this.aleatorio = aleatorio;
		this.insercion = insercion;
		this.modificacion = modificacion;
		this.seleccionada = seleccionada;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@JsonProperty("id") 
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Entradaid", referencedColumnName = "id")	
	public Entrada getEntrada() {
		return this.entrada;
	}

	public void setEntrada(Entrada entrada) {
		this.entrada = entrada;
	}

	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ReglaNegocioElementoid", referencedColumnName = "Elementoid")		
	public ReglaNegocio getReglaNegocio() {
		return this.reglaNegocio;
	}

	public void setReglaNegocio(ReglaNegocio reglaNegocio) {
		this.reglaNegocio = reglaNegocio;
	}

	@Column(name = "valor", nullable = false, length = 2000)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "valido")
	public Boolean getValido() {
		return this.valido;
	}

	public void setValido(Boolean valido) {
		this.valido = valido;
	}
	
	@Column(name = "correcto")
	public Boolean getCorrecto(){
		return this.correcto;
	}
	
	public void setCorrecto(Boolean correcto){
		this.correcto = correcto;
	}
	
	@Column(name = "registrado")
	public Boolean getRegistrado(){
		return this.registrado;
	}
	
	public void setRegistrado(Boolean registrado){
		this.registrado = registrado;
	}
	
	@Column(name = "aleatorio")
	public Boolean getAleatorio() {
		return aleatorio;
	}
	
	public void setAleatorio(Boolean aleatorio) {
		this.aleatorio = aleatorio;
	}
	
	@Column(name = "insercion")
	public Boolean getInsercion(){
		return this.insercion;
	}
	
	public void setInsercion(Boolean insercion){
		this.insercion = insercion;
	}
	
	@Column(name = "modificacion")
	public Boolean getModificacion() {
		return modificacion;
	}
	
	public void setModificacion(Boolean modificacion) {
		this.modificacion = modificacion;
	}

	@Column(name = "seleccionada")
	public Boolean getSeleccionada() {
		return seleccionada;
	}
	
	public void setSeleccionada(Boolean seleccionada) {
		this.seleccionada = seleccionada;
	}	
	@Column(name = "correcto_prueba")
	public Boolean getCorrecto_prueba() {
		return correcto_prueba;
	}
	
	public void setCorrecto_prueba(Boolean correcto_prueba) {
		this.correcto_prueba = correcto_prueba;
	}
	
	@Column(name = "correcto_guion")
	public Boolean getCorrecto_guion() {
		return correcto_guion;
	}
	
	public void setCorrecto_guion(Boolean correcto_guion) {
		this.correcto_guion = correcto_guion;
	}
}
