package mx.prisma.generadorPruebas.model;

// Generated 05-nov-2015 19:22:29 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import mx.prisma.editor.model.MensajeParametro;
import mx.prisma.editor.model.ReferenciaParametro;
import mx.prisma.editor.model.Trayectoria;

/**
 * ValorMensajeParametro generated by hbm2java
 */
@Entity
@Table(name = "ValorMensajeParametroTrayectoria", catalog = "PRISMA")
public class ValorMensajeParametroTrayectoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private MensajeParametro mensajeParametro;
	private String valor;
	private ReferenciaParametro referenciaParametro;
	private Trayectoria trayectoria;

	public ValorMensajeParametroTrayectoria() {
	}

	public ValorMensajeParametroTrayectoria(MensajeParametro mensajeParametro, String valor,
			ReferenciaParametro referenciaParametro, Trayectoria trayectoria) {
	//	this.mensajeParametro = mensajeParametro;
		this.valor = valor;
		this.referenciaParametro = referenciaParametro;
		this.trayectoria = trayectoria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "MensajeParametroTrayectoriaid", referencedColumnName = "id")	
	public MensajeParametro getMensajeParametro() {
		return this.mensajeParametro;
	}

	public void setMensajeParametro(MensajeParametro mensajeParametro) {
		this.mensajeParametro = mensajeParametro;
	}

	@Column(name = "valor", nullable = false, length = 2000)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ReferenciaParametroTrayectoriaid", referencedColumnName = "id")	
	public ReferenciaParametro getReferenciaParametro() {
		return this.referenciaParametro;
	}

	public void setReferenciaParametro(ReferenciaParametro referenciaParametro) {
		this.referenciaParametro = referenciaParametro;
	}
	
	@ManyToOne
    @JoinColumn(name = "TrayectoriaMensajeParametroid", referencedColumnName = "id")		
	public Trayectoria getTrayectoria() {
		return this.trayectoria;
	}

	public void setTrayectoria(Trayectoria trayectoria) {
		this.trayectoria = trayectoria;
	}

}