package mx.prisma.generadorPruebas.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import mx.prisma.editor.model.Accion;
import mx.prisma.editor.model.Entrada;
import mx.prisma.editor.model.Trayectoria;

/**
 * ValorEntradaTrayectoria generated by hbm2java
 */
@Entity
@Table(name = "ValorAccionTrayectoria", catalog = "PRISMA")
public class ValorAccionTrayectoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Accion accion;
	private Trayectoria trayectoria;
	private String urlDestino;
	private String metodo;

	public ValorAccionTrayectoria() {
	}

		
	public ValorAccionTrayectoria(Accion accion, Trayectoria trayectoria, String urlDestino) {
		this.accion = accion;
		this.trayectoria = trayectoria;
		this.urlDestino = urlDestino;
	}

	public ValorAccionTrayectoria(Accion accion, Trayectoria trayectoria,
			String urlDestino, String metodo) {
		this.accion = accion;
		this.trayectoria = trayectoria;
		this.urlDestino = urlDestino;
		this.metodo = metodo;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
    @JoinColumn(name = "AccionTrayectoriaid", referencedColumnName = "id")	
	public Accion getAccion() {
		return this.accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}

	@ManyToOne
    @JoinColumn(name = "TrayectoriaAccionid", referencedColumnName = "id")		
	public Trayectoria getTrayectoria() {
		return this.trayectoria;
	}

	public void setTrayectoria(Trayectoria trayectoria) {
		this.trayectoria = trayectoria;
	}

	@Column(name = "urlDestino", nullable = true, length = 2000)
	public String getUrlDestino() {
		return this.urlDestino;
	}

	public void setUrlDestino(String urlDestino) {
		this.urlDestino = urlDestino;
	}
	
	@Column(name = "metodo", nullable = true, length = 10)
	public String getMetodo() {
		return this.metodo;
	}

	public void setMetodo(String metodo) {
		this.metodo = metodo;
	}
}