package mx.prisma.generadorPruebas.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import mx.prisma.editor.model.Entrada;
import mx.prisma.editor.model.Trayectoria;

/**
 * ValorEntradaTrayectoria generated by hbm2java
 */
@Entity
@Table(name = "ValorEntradaTrayectoria", catalog = "PRISMA")
public class ValorEntradaTrayectoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Entrada entrada;
	private Trayectoria trayectoria;
	private String valor;
	private Boolean valido;

	public ValorEntradaTrayectoria() {
	}

	public ValorEntradaTrayectoria(Entrada entrada, Trayectoria trayectoria, String valor) {
		this.entrada = entrada;
		this.trayectoria = trayectoria;
		this.valor = valor;
	}

	public ValorEntradaTrayectoria(Entrada entrada, Trayectoria trayectoria,
			String valor, Boolean valido) {
		this.entrada = entrada;
		this.trayectoria = trayectoria;
		this.valor = valor;
		this.valido = valido;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
    @JoinColumn(name = "EntradaTrayectoriaid", referencedColumnName = "id")	
	public Entrada getEntrada() {
		return this.entrada;
	}

	public void setEntrada(Entrada entrada) {
		this.entrada = entrada;
	}

	@ManyToOne
    @JoinColumn(name = "TrayectoriaEntradaid", referencedColumnName = "id")		
	public Trayectoria getTrayectoria() {
		return this.trayectoria;
	}

	public void setTrayectoria(Trayectoria trayectoria) {
		this.trayectoria = trayectoria;
	}

	@Column(name = "valor", nullable = false, length = 2000)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}
	
	@Column(name = "valido")
	public Boolean getValido() {
		return this.valido;
	}

	public void setValido(Boolean valido) {
		this.valido = valido;
	}

/*@EmbedderId
 * private idValorEntradaTrayectoria (se crea su propia clase con sus settes y getters @Embeddable)
 * 
 * 
 * 
 * */	
	
}