package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

import mx.prisma.admin.model.Proyecto;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "Mensaje", catalog = "PRISMA")
@PrimaryKeyJoinColumn(name = "Elementoid", referencedColumnName = "id")
//@JsonTypeName("mensaje")
public class Mensaje extends Elemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String redaccion;
	private boolean parametrizado;
	private Set<MensajeParametro> parametros = new HashSet<MensajeParametro>(0);

	public Mensaje() {
	}

	public Mensaje(String clave, String numero, String nombre,
			Proyecto proyecto, String descripcion, EstadoElemento estadoElemento, String redaccion, boolean parametrizado) {
		super(clave, numero, nombre, proyecto, descripcion, estadoElemento);
		this.redaccion = redaccion;
		this.parametrizado = parametrizado;
	}

	@Column(name = "redaccion", nullable = false, length = 999)
	public String getRedaccion() {
		return this.redaccion;
	}

	public void setRedaccion(String redaccion) {
		this.redaccion = redaccion;
	}

	@Column(name = "parametrizado", nullable = false)
	public boolean isParametrizado() {
		return this.parametrizado;
	}

	public void setParametrizado(boolean parametrizado) {
		this.parametrizado = parametrizado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mensaje", cascade = CascadeType.ALL)	
	public Set<MensajeParametro> getParametros() {
		return parametros;
	}

	public void setParametros(Set<MensajeParametro> parametros) {
		this.parametros = parametros;
	}
	
	@JsonIgnore
	@Transient
	public String getType() {
		return "mensaje";
	}
	

}
