package mx.prisma.editor.model;

// Generated 07-jun-2015 17:10:34 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Salida generated by hbm2java
 */
@Entity
@Table(name = "Salida", catalog = "PRISMA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"CasoUsoElementoid", "MensajeElementoid", "TerminoGlosarioElementoid",
		"Atributoid" }))
public class Salida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TipoParametro tipoParametro;
	private CasoUso casoUso;
	private Mensaje mensaje;
	private Atributo atributo;
	private TerminoGlosario terminoGlosario;

	public Salida() {
	}

	public Salida(TipoParametro tipoParametro, CasoUso casoUso) {
		this.tipoParametro = tipoParametro;
		this.casoUso = casoUso;
	}

	public Salida(TipoParametro tipoParametro, CasoUso casoUso,
			Mensaje mensaje, TerminoGlosario terminoGlosario,
			Atributo atributo) {
		this.tipoParametro = tipoParametro;
		this.casoUso = casoUso;
		this.mensaje = mensaje;
		this.terminoGlosario = terminoGlosario;
		this.atributo = atributo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TipoParametroid", referencedColumnName = "id")
	public TipoParametro getTipoParametro() {
		return tipoParametro;
	}

	public void setTipoParametro(TipoParametro tipoParametro) {
		this.tipoParametro = tipoParametro;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CasoUsoElementoid", referencedColumnName = "Elementoid")
	public CasoUso getCasoUso() {
		return casoUso;
	}

	public void setCasoUso(CasoUso casoUso) {
		this.casoUso = casoUso;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "MensajeElementoid", referencedColumnName = "Elementoid")
	public Mensaje getMensaje() {
		return mensaje;
	}

	public void setMensaje(Mensaje mensaje) {
		this.mensaje = mensaje;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Atributoid", referencedColumnName = "id")
	public Atributo getAtributo() {
		return atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TerminoGlosarioElementoid", referencedColumnName = "Elementoid")
	public TerminoGlosario getTerminoGlosario() {
		return terminoGlosario;
	}

	public void setTerminoGlosario(TerminoGlosario terminoGlosario) {
		this.terminoGlosario = terminoGlosario;
	}

}
